language: java
jdk:
  - openjdk11
env:
  - TERM=dumb
before_install:
  - chmod +x gradlew
script: ./gradlew build check
after_success:
  - ./gradlew jacocoTestReport coveralls
notifications:
  email: false
