# heroku profile

spring:
  datasource:
      url: ${MYSQL_URI}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driverClassName: com.mysql.jdbc.Driver
      tomcat:
        max-active: 3
        max-idle: 2
        min-idle: 1
        initial-size: 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO
    io.github.aosn.mosaic: DEBUG

security:
  basic:
    enabled: false

vaadin:
  servlet:
    production-mode: true

mosaic:
  issue:
    organization: ${GITHUB_ORG:aosn}
    repository: ${GITHUB_REPO:aosn.github.io}
    filter: ${LABEL_FILTER:%sパート提案}
  slack:
    webhook: ${SLACK_WEBHOOK}
    channel: ${SLACK_CHANNEL}
    username: ${SLACK_NAME:Mosaic}
    template:
      begin: ${SLACK_MESSAGE_BEGIN:「%s」が開始されました。投票を行ってください。 https://vote.aosn.ws/}
      end: ${SLACK_MESSAGE_END:「%s」が終了しました。結果を確認してください。 https://vote.aosn.ws/}

# Production application token
github:
  client:
    clientId: ${GITHUB_CLIENT_ID}
    clientSecret: ${GITHUB_CLIENT_SECRET}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
